import {
  CodeBlock,
  Diagram,
  H2,
  H3,
  Line,
  Note,
  Table,
} from "@/components/learn/DocParts";
import type { Bi } from "@/lib/curriculum";

/** Section anchors — consumed by the "on this page" rail. */
export const headings: { id: string; label: Bi }[] = [
  {
    id: "the-problem",
    label: { bn: "টাইটেলে 'Create Next App'", en: "'Create Next App' in the title" },
  },
  {
    id: "architecture",
    label: { bn: "Metadata inheritance pipeline", en: "The metadata inheritance pipeline" },
  },
  {
    id: "mechanisms",
    label: { bn: "৩টি আর্কিটেকচারাল কনসেপ্ট", en: "Three architectural concepts" },
  },
  {
    id: "implementation",
    label: { bn: "Layout ও page মেটাডেটা", en: "Layout & page metadata" },
  },
  {
    id: "matrix",
    label: { bn: "Manual head vs Metadata API", en: "Manual head vs the Metadata API" },
  },
  {
    id: "takeaway",
    label: { bn: "Production Takeaways", en: "Production takeaways" },
  },
];

export default function MetadataApi() {
  return (
    <article className="doc-prose">
      {/* ── The problem ───────────────────────────────────────────────── */}
      <H2 id="the-problem" anchorOnly>
        টাইটেলে &apos;Create Next App&apos;
      </H2>

      <p>
        রাত ৯:৩০। ভুলু ভাই তার নতুন ই-কমার্স লিংক গুগলে সার্চ করে ও হোয়াটসঅ্যাপে শেয়ার করে মাথায় হাত
        দিয়ে বসে আছেন — মেটা টাইটেলে দেখাচ্ছে &quot;Create Next App&quot;, ডেসক্রিপশনে
        &quot;Generated by create next app&quot;। তিনি পেজে <code>&lt;head&gt;&lt;title&gt;</code>{" "}
        বসিয়েছিলেন, কিন্তু সার্ভার কম্পোনেন্ট তা ইগনোর করেছে।
      </p>

      <Line name="ভুলু ভাই">
        ফাহিম! আমার প্রোডাক্ট পেজের টাইটেল ও ডেসক্রিপশন গুগলে ঠিকমতো দেখাচ্ছে না কেন? আমি তো রিঅ্যাক্ট
        অ্যাপের মতো ম্যানুয়ালি <code>&lt;head&gt;</code> ও <code>&lt;title&gt;</code> বসিয়েছিলাম!
      </Line>

      <Line name="ফাহিম">
        ভুলু ভাই! App Router-এ সাধারণ <code>&lt;head&gt;</code> বা react-helmet ব্যবহারের দিন শেষ। RSC
        আর্কিটেকচারে পেজ সম্পূর্ণ রেন্ডার হওয়ার আগেই সার্চ ইঞ্জিন ক্রলারকে সঠিক মেটাডেটা পাঠাতে হয় —
        এজন্য Next.js এনেছে নেটিভ Metadata API।
      </Line>

      <Line name="নেক্সট-ভাই">
        একদম! আপনি স্রেফ একটি <code>metadata</code> অবজেক্ট এক্সপোর্ট করলেই সার্ভার-সাইড রেন্ডারিং
        ইঞ্জিন HTML-এর <code>&lt;head&gt;</code>-এ পারফেক্ট মেটা ট্যাগ জেনারেট করে দেয় — আর লেআউট থেকে
        পেজ লেভেলে মেটাডেটা সুন্দরভাবে ইনহেরিট ও মার্জ হয়।
      </Line>

      {/* ── Architecture ──────────────────────────────────────────────── */}
      <H2 id="architecture">১. Metadata Inheritance &amp; Cascade Architecture</H2>

      <Diagram>{`┌─────────────────────────────────────────────────────────────────────────┐
│                  NEXT.JS METADATA INHERITANCE PIPELINE                  │
└─────────────────────────────────────────────────────────────────────────┘

 Root layout (app/layout.tsx)
 ├── metadataBase: new URL('https://mysite.com')
 └── title: { template: '%s | TechCorp', default: 'TechCorp Enterprise' }
                        │
                        ▼ (inherits & merges the layout rules)
 Dashboard layout (app/dashboard/layout.tsx)
 └── description: 'Internal management dashboard'
                        │
                        ▼ (overrides the title, filling the template slot)
 Page (app/dashboard/analytics/page.tsx)
 └── title: 'Realtime Analytics'
                        │
                        ▼
 Server HTML response:
 <title>Realtime Analytics | TechCorp</title>
 <meta name="description" content="Internal management dashboard" />`}</Diagram>

      {/* ── Mechanisms ────────────────────────────────────────────────── */}
      <H2 id="mechanisms">২. কোর আর্কিটেকচারাল কনসেপ্ট</H2>

      <p>
        <strong>Static metadata export:</strong> <code>layout.tsx</code> বা <code>page.tsx</code>-এ
        টাইপ-সেফ <code>Metadata</code> অবজেক্ট এক্সপোর্ট করলে Next.js সার্ভার রেন্ডারিংয়ের সময়ই HTML-এর{" "}
        <code>&lt;head&gt;</code> তৈরি করে ফেলে।
      </p>

      <p>
        <strong>Cascade &amp; title templates:</strong> রুট লেআউটের মেটাডেটা সাব-লেআউট ও পেজে
        স্বয়ংক্রিয়ভাবে ইনহেরিট হয়। <code>title.template</code> দিয়ে সব পেজের টাইটেলে ব্র্যান্ড নেম
        ডাইনামিকভাবে যুক্ত করা যায় (<code>Title | Brand</code>)।
      </p>

      <p>
        <strong>metadataBase absolute resolution:</strong> সোশ্যাল শেয়ারিং ও ক্যানোনিকাল URL-এর জন্য{" "}
        <code>metadataBase</code> অত্যন্ত গুরুত্বপূর্ণ — রুট লেআউটে সেট করলে সব রিলেটিভ ইমেজ ও পাথ
        স্বয়ংক্রিয়ভাবে absolute URL-এ রূপান্তরিত হয়।
      </p>

      {/* ── Implementation ────────────────────────────────────────────── */}
      <H2 id="implementation">৩. Production Code Implementation</H2>

      <H3>❌ Anti-pattern — hand-written head tags in a server component</H3>

      <CodeBlock filename="app/broken-seo/page.tsx">{`// 🔴 POOR PRACTICE: manual head tags inside a React Server Component
// breaks server streaming and produces console warnings + SEO failures

export default function BrokenSEOPage() {
  return (
    <div>
      {/* ❌ never do this in the App Router */}
      <head>
        <title>My E-Commerce Store</title>
        <meta name="description" content="Buy awesome products here!" />
      </head>
      <h1>Welcome to the store</h1>
    </div>
  );
}`}</CodeBlock>

      <H3>🟢 Production pattern — a scalable metadata cascade</H3>

      <CodeBlock filename="app/layout.tsx">{`// 🟢 PRODUCTION PATTERN: root layout metadata
import type { Metadata } from 'next';

export const metadata: Metadata = {
  // 🟢 resolves relative OpenGraph/Twitter image paths globally
  metadataBase: new URL('https://enterpriseapp.com'),

  // 🟢 the template wraps every child page title
  title: {
    default: 'Enterprise System — Scalable Web Architecture',
    template: '%s | Enterprise System',
  },
  description: 'Production-ready enterprise SaaS platform with high discoverability.',
  keywords: ['Next.js', 'React', 'TypeScript', 'SEO', 'Web Development'],
  authors: [{ name: 'Zubayer Salehin' }],
  creator: 'Zubayer Salehin',
  publisher: 'Enterprise Architecture Ltd.',

  // 🟢 crawler directives, applied app-wide
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
    },
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="bn">
      <body>{children}</body>
    </html>
  );
}`}</CodeBlock>

      <CodeBlock filename="app/dashboard/analytics/page.tsx">{`import type { Metadata } from 'next';

// 🟢 overrides the title while automatically filling the parent template
export const metadata: Metadata = {
  title: 'Realtime Analytics', // renders as "Realtime Analytics | Enterprise System"
  description: 'Monitor real-time user retention and transaction throughput.',
  // metadataBase, authors and robots are inherited from the root layout
};

export default function AnalyticsPage() {
  return (
    <main className="p-8">
      <h1 className="text-2xl font-bold">Analytics Dashboard</h1>
    </main>
  );
}`}</CodeBlock>

      {/* ── Matrix ────────────────────────────────────────────────────── */}
      <H2 id="matrix">৪. Manual &lt;head&gt; vs. the Metadata API</H2>

      <Table
        head={["বৈশিষ্ট্য", "Manual <head>", "Metadata API"]}
        rows={[
          [
            "Execution context",
            "ক্লায়েন্ট DOM ইনজেকশন 🔴",
            "সার্ভার-সাইড স্ট্রিমিং ও পার্সিং 🟢",
          ],
          [
            "Inheritance model",
            "প্রতিটি পেজে কপি-পেস্ট 🔴",
            "লেআউট থেকে চাইল্ডে অটো-মার্জ 🟢",
          ],
          [
            "Type safety",
            "স্পেলিং ভুলে ব্রোকেন মেটা ট্যাগ 🔴",
            <span key="d">
              TypeScript-এর পূর্ণ <code>Metadata</code> টাইপ 🟢
            </span>,
          ],
          [
            "Hydration cost",
            "DOM mismatch ও ফ্লিকার 🔴",
            "জিরো ক্লায়েন্ট JS ওভারহেড 🟢",
          ],
        ]}
      />

      <Line name="ভুলু ভাই">
        দুর্দান্ত ফাহিম! <code>export const metadata</code> ব্যবহারের পর রুট লেআউটের সাথে চাইল্ড পেজের
        টাইটেল সুন্দর অটো-মার্জ হয়ে গেল! হোয়াটসঅ্যাপে লিংক পাঠালেই এখন সঠিক ব্র্যান্ড নাম ও টাইটেল
        দেখাচ্ছে।
      </Line>

      {/* ── Takeaways ─────────────────────────────────────────────────── */}
      <H2 id="takeaway">Production Takeaways</H2>

      <Note>
        <ul>
          <li>
            <strong>Always set metadataBase:</strong> রুট লেআউটে{" "}
            <code>metadataBase: new URL(&apos;https://yourdomain.com&apos;)</code> সেট করা
            বাধ্যতামূলক — নাহলে সোশ্যাল ও OG-এর রিলেটিভ URL কাজ করবে না।
          </li>
          <li>
            <strong>Utilize title.template:</strong> প্রতিটি পেজে ব্র্যান্ড নাম না লিখে রুট লেআউটে{" "}
            <code>template: &apos;%s | Brand&apos;</code> ব্যবহার করুন।
          </li>
          <li>
            <strong>Never render raw head tags:</strong> App Router প্রজেক্টে হাতে{" "}
            <code>&lt;head&gt;</code> বা <code>&lt;meta&gt;</code> লিখবেন না — সব কাজ{" "}
            <code>metadata</code> অবজেক্টে করুন।
          </li>
        </ul>
      </Note>
    </article>
  );
}
